mac_address: 40DD1386-BC20-4A5C-9744-EC13004C1227
stand_height: 1111
sit_height: 764
height_tolerance: 2.0
scan_timeout: 5
connection_timeout: 10
movement_timeout: 30
adapter_name: hci0
server_address: "127.0.0.1"
server_port: 9123
