cask_args appdir: "/Applications"
tap "caskroom/cask"
tap "thefox/brewery"

brew "ansible"
brew "composer"
brew "curl"
brew "ffmpeg"
brew "cmus", args: ['with-ffmpeg', 'HEAD']
brew "git"
brew "git-flow"
brew "htop"
brew "jq"
brew "mas"
brew "mtr"
brew "nmap"
brew "openssl"
brew "pv"
brew "reattach-to-user-namespace"
brew "rsync"
brew "sqlite"
brew "ssh-copy-id"
brew "tig"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"

brew "cmus-control", restart_service: "changed"
brew "mysql", restart_service: "changed"

cask "alfred"
cask "appcleaner"
cask "bettertouchtool"
cask "cheatsheet"
cask "dbeaver-community"
cask "firefox"
cask "google-chrome"
cask "libreoffice"
cask "phpstorm"
cask "pycharm"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "the-unarchiver"
cask "transmission"
cask "vagrant"
# cask "virtualbox" // Doesn't currently work, retry later
cask "vlc"
cask "whatsapp"

mas "Gestimer", id: 990588172
mas "iA Writer", id: 775737590
mas "Telephone", id: 406825478

