cask_args appdir: "/Applications"
tap "caskroom/cask"

brew "ack"
brew "ansible"
brew "bash"
brew "bash-completion"
brew "composer"
brew "curl"
brew "git"
brew "git-flow"
brew "htop"
brew "jq"
brew "lynx"
brew "mtr"
brew "nmap"
brew "node"
brew "openssl"
brew "pv"
brew "python"
brew "rsync"
brew "ruby"
brew "sqlite"
brew "ssh-copy-id"
brew "tig"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"

brew "mysql@5.6", restart_service: true, link: true, conflicts_with: ["mysql"]

cask "firefox"
cask "google-chrome"
cask "java" unless system "/usr/libexec/java_home --failfast"
cask "phpstorm"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "vlc"
