#!/usr/bin/env bash

echo "performing full homebrew install"

sudo -v

brew update
brew upgrade

brew tap homebrew/versions
brew tap phinze/homebrew-cask

brew install ack
brew install bash
brew install brew-cask
brew install coreutils
brew install git
brew install grc
brew install htop-osx
brew install ssh-copy-id
brew install vim
brew install wget --enable-iri

brew cask install app-cleaner
brew cask install arq
brew cask install calibre
brew cask install dropbox
brew cask install firefox
brew cask install google-chrome
brew cask install gpgtools
brew cask install harvest
brew cask install iterm2
brew cask install lastfm
brew cask install miecraft
brew cask install mou
brew cask install netbeans
brew cask install sequel-pro
brew cask install skype
brew cask install sourcetree
brew cask install spotify
brew cask install steam
brew cask install sublime-text-3
brew cask install subtitles
brew cask install things
brew cask install transmission
brew cask install transmit
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc

brew cleanup
